"""TripleModel — Pydantic models backed by RDF graphs via pyoxigraph.

Install: ``pip install triplemodel``
"""

from triplemodel.config import (
    RDF,
    RDFS,
    RDF_TYPE,
    XSD,
    EmbedMode,
    GraphMode,
    RdfConfig,
    freeze_prefixes,
    get_graph_context,
    id_from_subject_uri,
    resolve_graph_iri,
    subject_base,
)
from triplemodel.fields import (
    IriId,
    InverseOf,
    Predicate,
    Transitive,
    rdf_field,
    ref_field,
)
from triplemodel.fields.resource_ref import ResourceRef
from triplemodel.terms.lang import Lang, LangString
from triplemodel.terms.opaque import OpaqueLiteral
from triplemodel.vocab_registry import VocabularyRegistry
from triplemodel.io import (
    OnDuplicate,
    PreparedModelQuery,
    SparqlQueryForm,
    all_from_dataset,
    all_from_dataset_dispatch,
    all_from_graph_dispatch,
    dump_dataset,
    dump_graph,
    dump_model,
    graph_to_model,
    graph_to_model_dispatch,
    graph_to_model_dispatch_from_dataset,
    graph_to_model_from_dataset,
    graph_to_models,
    graph_to_models_from_dataset,
    iter_graph_to_models,
    infer_format,
    is_quad_format,
    iter_model_quads,
    load_dataset,
    load_graph,
    load_models,
    load_models_from_dataset,
    load_models_from_graph,
    load_models_streaming,
    open_graph,
    parse_into_store_graph,
    graph_store_session,
    store_commit,
    store_rollback,
    destroy_store,
    model_to_dataset,
    model_to_graph,
    model_to_triples,
    models_to_dataset,
    models_to_graph,
    parse_into_dataset,
    parse_into_graph,
    parse_url_into_dataset,
    parse_url_into_graph,
    quads_in_context,
    sync_to_dataset,
    sync_to_graph,
    GraphDiff,
    apply_update,
    ask,
    cbd_graph,
    cbd_model,
    construct_models,
    detect_query_form,
    graph_diff,
    graph_from_construct_result,
    graphs_equal,
    hydrate_refs,
    init_bindings_from_model,
    init_ns_from_model,
    load_sparql,
    model_diff,
    model_join,
    open_sparql_graph,
    prepare_model_query,
    resolve_model_class_with_rdfs,
    run_sparql,
    select_models,
    subject_type_closure,
    subclass_uris,
    transitive_objects,
    transitive_subjects,
)
from triplemodel.io.ops import graph_set, graph_value, merge_graphs, objects_for_field
from triplemodel.model import TripleModel
from triplemodel.namespaces import bind_namespaces, expand_curie
from triplemodel.protocols import (
    RdfResource,
    register_rdf_resource,
    resolve_model_class,
)
from triplemodel.validation import validate_graph
from triplemodel.terms import LiteralRegistry, default_registry, register_literal_type

from triplemodel.store import Store

__version__ = "0.10.1"

__all__ = [
    "EmbedMode",
    "GraphMode",
    "Store",
    "IriId",
    "InverseOf",
    "Lang",
    "all_from_dataset",
    "all_from_dataset_dispatch",
    "all_from_graph_dispatch",
    "dump_dataset",
    "dump_graph",
    "dump_model",
    "get_graph_context",
    "graph_to_model_dispatch",
    "graph_to_model_dispatch_from_dataset",
    "graph_to_model_from_dataset",
    "graph_to_models_from_dataset",
    "infer_format",
    "iter_model_quads",
    "is_quad_format",
    "load_dataset",
    "load_graph",
    "load_models",
    "load_models_from_dataset",
    "load_models_from_graph",
    "load_models_streaming",
    "open_graph",
    "parse_into_store_graph",
    "model_to_dataset",
    "models_to_dataset",
    "parse_into_dataset",
    "parse_into_graph",
    "ref_field",
    "parse_url_into_dataset",
    "parse_url_into_graph",
    "quads_in_context",
    "resolve_graph_iri",
    "resolve_model_class",
    "validate_graph",
    "LangString",
    "LiteralRegistry",
    "OpaqueLiteral",
    "OnDuplicate",
    "Predicate",
    "Transitive",
    "VocabularyRegistry",
    "ResourceRef",
    "RDF",
    "RDFS",
    "RDF_TYPE",
    "XSD",
    "RdfConfig",
    "RdfResource",
    "TripleModel",
    "bind_namespaces",
    "default_registry",
    "expand_curie",
    "freeze_prefixes",
    "graph_set",
    "graph_to_model",
    "graph_to_models",
    "graph_store_session",
    "graph_value",
    "destroy_store",
    "iter_graph_to_models",
    "id_from_subject_uri",
    "merge_graphs",
    "model_to_graph",
    "model_to_triples",
    "models_to_graph",
    "objects_for_field",
    "rdf_field",
    "register_literal_type",
    "register_rdf_resource",
    "store_commit",
    "store_rollback",
    "subject_base",
    "sync_to_dataset",
    "sync_to_graph",
    "PreparedModelQuery",
    "SparqlQueryForm",
    "GraphDiff",
    "apply_update",
    "ask",
    "cbd_graph",
    "cbd_model",
    "construct_models",
    "detect_query_form",
    "graph_diff",
    "graph_from_construct_result",
    "graphs_equal",
    "hydrate_refs",
    "init_bindings_from_model",
    "init_ns_from_model",
    "load_sparql",
    "model_diff",
    "model_join",
    "open_sparql_graph",
    "prepare_model_query",
    "resolve_model_class_with_rdfs",
    "run_sparql",
    "select_models",
    "subject_type_closure",
    "subclass_uris",
    "transitive_objects",
    "transitive_subjects",
    "__version__",
]
