"""Emit TripleModel stub classes from OWL/RDFS graphs."""

from __future__ import annotations

import re
from urllib.parse import urlparse

from rdflib import Graph, URIRef
from rdflib.namespace import OWL, RDF, RDFS

_OWL_DATATYPE = URIRef(f"{OWL}DatatypeProperty")
_OWL_OBJECT = URIRef(f"{OWL}ObjectProperty")


def _local_name(uri: str) -> str:
    parsed = urlparse(uri)
    fragment = parsed.fragment
    if fragment:
        return re.sub(r"[^\w]", "_", fragment)
    path = parsed.path.rstrip("/")
    if path:
        return re.sub(r"[^\w]", "_", path.split("/")[-1])
    return "Resource"


def _class_name(uri: str) -> str:
    name = _local_name(uri)
    if not name or not name[0].isalpha():
        name = f"C_{name}"
    return name[:1].upper() + name[1:]


def _field_name(uri: str) -> str:
    name = _local_name(uri)
    if not name or not name[0].isalpha():
        name = f"f_{name}"
    return name


def _namespace_for(uri: str) -> str:
    parsed = urlparse(uri)
    if parsed.fragment:
        base = uri.split("#", 1)[0]
        return base if base.endswith(("/", "#")) else base + "#"
    path = parsed.path
    if "/" in path:
        return uri.rsplit("/", 1)[0] + "/"
    return uri + "/"


def generate_models_from_graph(graph: Graph) -> str:
    """Return Python source for stub ``TripleModel`` subclasses."""
    classes: dict[str, list[tuple[str, str, str]]] = {}
    for cls in graph.subjects(RDF.type, RDFS.Class):
        if isinstance(cls, URIRef):
            classes.setdefault(str(cls), [])
    for cls in graph.subjects(RDF.type, OWL.Class):
        if isinstance(cls, URIRef):
            classes.setdefault(str(cls), [])

    for pred_type in (_OWL_DATATYPE, _OWL_OBJECT):
        for prop in graph.subjects(RDF.type, pred_type):
            if not isinstance(prop, URIRef):
                continue
            prop_s = str(prop)
            fname = _field_name(prop_s)
            for domain in graph.objects(prop, RDFS.domain):
                if not isinstance(domain, URIRef):
                    continue
                domain_s = str(domain)
                py_type = "str"
                classes.setdefault(domain_s, []).append((prop_s, fname, py_type))

    parent_map: dict[str, str | None] = {uri: None for uri in classes}
    for subj, parent in graph.subject_objects(RDFS.subClassOf):
        if isinstance(subj, URIRef) and isinstance(parent, URIRef):
            parent_map[str(subj)] = str(parent)

    lines = [
        '"""Generated by triplemodel-codegen (experimental)."""',
        "",
        "from __future__ import annotations",
        "",
        "from triplemodel import TripleModel, rdf_field",
        "",
    ]
    emitted: set[str] = set()

    def emit_class(class_uri: str) -> None:
        if class_uri in emitted:
            return
        parent_uri = parent_map.get(class_uri)
        if parent_uri and parent_uri not in emitted:
            emit_class(parent_uri)
        emitted.add(class_uri)
        cname = _class_name(class_uri)
        ns = _namespace_for(class_uri)
        bases = "TripleModel"
        if parent_uri:
            bases = _class_name(parent_uri)
        lines.append(f"class {cname}({bases}):")
        lines.append("    class Rdf:")
        lines.append(f'        namespace = "{ns}"')
        lines.append(f'        type_uri = "{class_uri}"')
        lines.append('        id_field = "slug"')
        lines.append("")
        lines.append("    slug: str")
        seen_fields: set[str] = set()
        for prop_uri, fname, py_type in sorted(
            classes.get(class_uri, []), key=lambda x: x[1]
        ):
            if fname in seen_fields:
                continue
            seen_fields.add(fname)
            lines.append(f'    {fname}: {py_type} = rdf_field("{prop_uri}")')
        lines.append("")
        lines.append("")

    for class_uri in sorted(classes):
        emit_class(class_uri)

    return "\n".join(lines).rstrip() + "\n"
