name: Docs

on:
  push:
  pull_request:

jobs:
  sphinx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -e ".[docs]"
      - run: sphinx-build -b html docs docs/_build/html -W --keep-going
      - run: sphinx-build -b linkcheck docs docs/_build/linkcheck -W --keep-going
        continue-on-error: true
